/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_xmx_nativexbullet_NativeGravityTest */

#ifndef _Included_net_xmx_nativexbullet_NativeGravityTest
#define _Included_net_xmx_nativexbullet_NativeGravityTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_xmx_nativexbullet_NativeGravityTest
 * Method:    setGravityInXBullet
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_net_xmx_nativexbullet_NativeGravityTest_setGravityInXBullet
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
