/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_xmx_nativexbullet_Gravity */

#ifndef _Included_net_xmx_nativexbullet_Gravity
#define _Included_net_xmx_nativexbullet_Gravity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_xmx_nativexbullet_Gravity
 * Method:    setGravityInternal
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_net_xmx_nativexbullet_Gravity_setGravityInternal
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     net_xmx_nativexbullet_Gravity
 * Method:    getXBulletVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_xmx_nativexbullet_Gravity_getXBulletVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
